runtime: python39
entrypoint: gunicorn -b :$PORT -w 1 -t 0 app:app

env_variables:
  PYTHONBUFFERED: "True"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
